const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let pickerTarget,pickerCurrent,backupPath,lastFinished;
async function req(path,opts={}){const r=await fetch(path,{headers:{'content-type':'application/json'},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||r.statusText);return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bytes(n){const u=['B','KB','MB','GB','TB'];let v=+n||0,i=0;while(v>=1000&&i<4){v/=1000;i++}return `${v.toFixed(i?1:0)} ${u[i]}`}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),2500)}
async function state(){try{const s=await req('/api/state');$('#serverUrl').value=s.settings.server;const x=$('#serverStatus');x.className='status '+(s.server.online?'online':'offline');x.textContent=s.server.online?`Server online · ${s.server.stats.objects} objects`:`Server offline · ${s.server.error||'not configured'}`;activity(s.job);if(s.job&&s.job.status!=='running'&&lastFinished!==s.job.id){lastFinished=s.job.id;toast(s.job.status==='done'?'Operation complete':s.job.error);drives()}}catch(e){toast(e.message)}}
function activity(j){const e=$('#activity');if(!j){e.className='empty';e.textContent='Nothing running.';return}const p=j.progress||{},m=[];for(const [k,l] of [['scanned','scanned'],['new','new'],['duplicates','duplicates'],['ignored','ignored'],['copied','copied'],['already','already there'],['checked','checked'],['total','total'],['bad','bad']])if(p[k]!=null)m.push(`<span class="metric"><b>${esc(p[k])}</b> ${l}</span>`);if(p.uploaded)m.push(`<span class="metric"><b>${esc(p.uploaded)}</b> uploaded</span>`);if(p.copiedSize)m.push(`<span class="metric"><b>${esc(p.copiedSize)}</b> copied</span>`);e.className='activity';e.innerHTML=`<div class="activity-top"><div><div class="activity-title">${esc(j.label)}</div><div class="activity-phase ${j.status}">${esc(j.status==='running'?p.phase||'Working…':j.status==='done'?'Done':j.error)}</div></div><span class="badge">${j.status}</span></div>${p.current?`<div class="drive-path">${esc(p.current)}</div>`:''}<div class="metrics">${m.join('')}</div>`}
async function drives(){const e=$('#drives');e.innerHTML='<div class="muted">Looking for drives…</div>';try{const {roots}=await req('/api/roots');e.innerHTML=roots.map((d,i)=>`<div class="drive"><div class="drive-head"><div><div class="drive-name">${esc(d.managed?d.meta.name:d.path)}</div><div class="drive-path">${esc(d.path)}</div></div><span class="badge ${d.managed?'managed':''}">${d.managed?'Mochimono backup':'Available'}</span></div><div class="drive-meta">${bytes(d.freeBytes)} free of ${bytes(d.totalBytes)}</div><div class="drive-actions">${d.managed?`<button class="primary small" data-up="${i}">Update</button><button class="secondary small" data-st="${i}">Status</button><button class="secondary small" data-v="${i}">Verify</button>`:`<button class="primary small" data-init="${i}">Use for backup</button>`}</div></div>`).join('')||'<div class="muted">No drives found.</div>';$$('[data-up]').forEach(b=>b.onclick=()=>runBackup(roots[+b.dataset.up].path,'update'));$$('[data-v]').forEach(b=>b.onclick=()=>runBackup(roots[+b.dataset.v].path,'verify'));$$('[data-st]').forEach(b=>b.onclick=async()=>{try{const s=await req('/api/backup/status?path='+encodeURIComponent(roots[+b.dataset.st].path));toast(`${s.meta.name}: ${s.remote.protectedCount}/${s.remote.desiredCount} protected`)}catch(e){toast(e.message)}});$$('[data-init]').forEach(b=>b.onclick=()=>backupDialog(roots[+b.dataset.init].path))}catch(x){e.innerHTML=`<div class="error">${esc(x.message)}</div>`}}
async function runBackup(path,kind){try{await req('/api/backup/'+kind,{method:'POST',body:JSON.stringify({path})});state()}catch(e){toast(e.message)}}
async function picker(target){pickerTarget=target;const r=await req('/api/roots');$('#pickerRoots').innerHTML=r.roots.map((x,i)=>`<button data-r="${i}">${esc(x.path)}</button>`).join('');$$('[data-r]').forEach(b=>b.onclick=()=>folder(r.roots[+b.dataset.r].path));await folder(target.value||r.home);$('#folderDialog').showModal()}
async function folder(path){try{const d=await req('/api/browse?path='+encodeURIComponent(path));pickerCurrent=d.path;$('#pickerPath').textContent=d.path;$('#pickerUp').disabled=!d.parent;$('#pickerUp').dataset.parent=d.parent||'';$('#pickerDirs').innerHTML=d.directories.map((x,i)=>`<div class="folder" data-d="${i}">📁 ${esc(x.name)}</div>`).join('')||'<div class="folder muted">No subfolders</div>';$$('[data-d]').forEach(x=>x.onclick=()=>folder(d.directories[+x.dataset.d].path))}catch(e){toast(e.message)}}
function backupDialog(path){backupPath=path;$('#backupPathLabel').textContent=path;$('#backupName').value='';$('#backupEverything').checked=true;$('#backupTypes').classList.add('disabled');$$('#backupTypes input').forEach(i=>i.checked=false);$('#backupDialog').showModal()}
$('#browseImport').onclick=()=>picker($('#importPath'));$('#pickerUp').onclick=()=>folder($('#pickerUp').dataset.parent);$('#pickerChoose').onclick=()=>{pickerTarget.value=pickerCurrent;$('#folderDialog').close()};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#backupEverything').onchange=e=>$('#backupTypes').classList.toggle('disabled',e.target.checked);$('#refreshDrives').onclick=drives;
$('#startImport').onclick=async()=>{const path=$('#importPath').value.trim();if(!path)return toast('Choose a folder first');try{await req('/api/import',{method:'POST',body:JSON.stringify({path,source:$('#sourceName').value.trim()})});state()}catch(e){toast(e.message)}};
$('#initializeBackup').onclick=async()=>{const types=$('#backupEverything').checked?[]:$$('#backupTypes input:checked').map(i=>i.value);try{await req('/api/backup/init',{method:'POST',body:JSON.stringify({path:backupPath,name:$('#backupName').value.trim(),types})});$('#backupDialog').close();toast('Backup initialized');drives()}catch(e){toast(e.message)}};
$('#saveSettings').onclick=async()=>{try{await req('/api/settings',{method:'POST',body:JSON.stringify({server:$('#serverUrl').value.trim(),token:$('#serverToken').value})});$('#serverToken').value='';toast('Settings saved');state()}catch(e){toast(e.message)}};
state();drives();setInterval(state,900);