import { ExperimentalWebGLMapRenderer } from './experimental-webgl-map.js';

const files=document.querySelector('#files'),sort=document.querySelector('#sort'),mediaSize=document.querySelector('#mediaSize');
const MODE_KEY='mochimono-experimental-view-mode',WORKER_REV='20260912-7',THUMB_VERSION=3,MAX_MAP_ZOOM=48;
const MODES={
  mosaic:{label:'Mosaic',description:'True 2D neighbor optimization with visual families locked together'},
  'color-map':{label:'Color Map',description:'Hue × lightness map with visual families co-located'},
  'family-quilt':{label:'Family Quilt',description:'Verified perceptual families as contiguous visual blocks'},
  atlas:{label:'AI Atlas',description:'2D DINO + SigLIP neighborhood map'},
  'semantic-rooms':{label:'Semantic Rooms',description:'Named SigLIP concepts as spatial rooms'},
  'time-appearance':{label:'Time × Appearance',description:'Chronology horizontally, visual character vertically'}
};
let mode=MODES[localStorage.getItem(MODE_KEY)]?localStorage.getItem(MODE_KEY):'mosaic';
let wanted=false,sourceModel=null,wrappedGrid=null,baseSetModel=null,worker=null,generation=0,runTimer=0,result=null,media=[],cell=96,gridColumns=8;
let mapZoom=1,mapPanX=0,mapPanY=0,drag=null,renderFrame=0,mapSettleTimer=0,mapRenderer=null,indexPosition=new Map();
const mounted=new Map(),cache=new Map();

const option=document.createElement('option');option.value='experimental';option.textContent='Experimental';option.title='Experimental media layouts';
if(sort&&!sort.querySelector('option[value="experimental"]')){const ai=sort.querySelector('option[value="ai-global"]');ai?ai.after(option):sort.append(option)}
const style=document.createElement('style');style.textContent=`
html.experimental-view-active,html.experimental-view-active body{overflow-x:hidden}
.experimental-view-bar,.experimental-view-surface{width:calc(100vw - 20px);max-width:none;box-sizing:border-box;margin-left:calc(50% - 50vw + 10px);margin-right:0}
.experimental-view-bar{margin-top:8px;margin-bottom:6px;padding:8px 10px;display:flex;align-items:center;gap:8px;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:#171518;color:#d8cfcb;position:sticky;top:6px;z-index:20}
.experimental-view-bar[hidden],.experimental-view-surface[hidden]{display:none!important}.experimental-view-bar strong{font-size:11px;white-space:nowrap}.experimental-view-modes{display:flex;gap:3px;flex-wrap:wrap}.experimental-view-modes button{height:25px;padding:0 8px;border:0;border-radius:7px;background:transparent;color:#8e8582;font-size:10px;font-weight:650}.experimental-view-modes button:hover{background:#252126;color:#ddd5d1}.experimental-view-modes button.active{background:#eee8e4;color:#171416}.experimental-view-status{min-width:0;flex:1;color:#8e8582;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.experimental-view-fit,.experimental-view-close{height:28px;border:0;border-radius:8px;background:transparent;color:#a09794}.experimental-view-fit:hover,.experimental-view-close:hover{background:#29252a;color:#fff}.experimental-view-close{width:30px;font-size:18px}
.experimental-view-surface{position:relative;height:max(520px,calc(100dvh - 116px));min-height:520px;border:1px solid rgba(255,255,255,.06);border-radius:10px;overflow:hidden;background:#0e0d0f;contain:layout paint style}.experimental-view-viewport{position:absolute;inset:0;overflow:hidden;touch-action:none;outline:0;background:#0e0d0f;cursor:grab}.experimental-view-viewport.dragging{cursor:grabbing}.experimental-view-viewport.over-media:not(.dragging){cursor:pointer}.experimental-view-viewport.grid-mode{overflow:auto;touch-action:auto;cursor:default}.experimental-view-canvas{position:absolute;inset:0;width:100%;height:100%;display:block;z-index:1;background:#0e0d0f}.experimental-view-canvas[hidden]{display:none}.experimental-view-plane{position:absolute;left:0;top:0;transform-origin:0 0;will-change:transform;contain:layout paint style;z-index:2}.experimental-view-viewport:not(.grid-mode) .experimental-view-plane{pointer-events:none}.experimental-view-rooms,.experimental-view-cards{position:absolute;inset:0}.experimental-view-room{position:absolute;border:1px solid rgba(255,255,255,.11);border-radius:8px;background:rgba(255,255,255,.018);pointer-events:none;box-sizing:border-box}.experimental-view-room>span{position:sticky;left:6px;top:5px;display:inline-block;margin:5px;padding:3px 6px;border-radius:6px;background:rgba(14,13,15,.78);backdrop-filter:blur(5px);font-size:10px;font-weight:700;color:#ddd4d0}.experimental-view-marker{position:absolute;z-index:4;padding:2px 5px;border-radius:5px;background:rgba(14,13,15,.75);font-size:9px;font-weight:700;color:#d4cbc7;pointer-events:none;white-space:nowrap}.experimental-card{position:absolute;padding:0;border:0;border-radius:3px;overflow:hidden;background:#171518;box-shadow:0 0 0 1px rgba(255,255,255,.035);cursor:pointer;contain:strict}.experimental-card img{display:block;width:100%;height:100%;object-fit:cover;background:#151316;pointer-events:none}.experimental-view-loading{position:absolute;inset:0;display:grid;place-items:center;color:#8e8582;font-size:12px;pointer-events:none;z-index:8}.experimental-view-loading[hidden]{display:none}html.experimental-view-active #dateRail,html.experimental-view-active .ai-global-rail{display:none!important}
@media(max-width:700px){.experimental-view-bar,.experimental-view-surface{width:calc(100vw - 8px);margin-left:calc(50% - 50vw + 4px)}.experimental-view-bar{top:4px;padding:6px}.experimental-view-surface{height:max(460px,calc(100dvh - 94px));min-height:460px;border-radius:8px}}`;document.head.append(style);
const bar=document.createElement('div');bar.className='experimental-view-bar';bar.hidden=true;bar.innerHTML=`<strong>Experiments</strong><div class="experimental-view-modes">${Object.entries(MODES).map(([key,value])=>`<button type="button" data-experimental-mode="${key}" title="${value.description}">${value.label}</button>`).join('')}</div><span class="experimental-view-status"></span><button class="experimental-view-fit" type="button">Fit</button><button class="experimental-view-close" type="button" title="Return to newest">×</button>`;files?.before(bar);
const surface=document.createElement('section');surface.className='experimental-view-surface';surface.hidden=true;surface.innerHTML='<div class="experimental-view-viewport" tabindex="0"><canvas class="experimental-view-canvas" hidden></canvas><div class="experimental-view-plane"><div class="experimental-view-rooms"></div><div class="experimental-view-cards"></div></div><div class="experimental-view-loading" hidden></div></div>';bar.after(surface);
const viewport=surface.querySelector('.experimental-view-viewport'),mapCanvas=surface.querySelector('.experimental-view-canvas'),plane=surface.querySelector('.experimental-view-plane'),roomsLayer=surface.querySelector('.experimental-view-rooms'),cardsLayer=surface.querySelector('.experimental-view-cards'),loading=surface.querySelector('.experimental-view-loading'),status=bar.querySelector('.experimental-view-status'),fitButton=bar.querySelector('.experimental-view-fit');

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char]));
const ratio=item=>Math.max(1,Number(item?.width)||1)/Math.max(1,Number(item?.height)||1);
const layoutRatio=item=>Math.max(.5,Math.min(2,ratio(item)));
function fitAspect(item,boxW,boxH){const r=ratio(item),br=boxW/Math.max(.0001,boxH);return r>=br?[boxW,boxW/r]:[boxH*r,boxH]}
function syncButtons(){bar.querySelectorAll('[data-experimental-mode]').forEach(button=>button.classList.toggle('active',button.dataset.experimentalMode===mode))}
function setStatus(text){status.textContent=String(text||'')}
function setLoading(text=''){loading.hidden=!text;loading.textContent=text}
function hashText(value,seed=2166136261){let hash=seed>>>0;for(let i=0;i<value.length;i++){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619)>>>0}return(hash^(hash>>>16))>>>0}
function mediaIdentity(items){let sum=0,xor=0;for(const item of items){const value=hashText(`${item.hash}:${item.width}x${item.height}:${item.dateMs}`);sum=(sum+value)>>>0;xor^=value}return`${items.length}:${sum.toString(36)}:${(xor>>>0).toString(36)}`}
function sourceItems(){return Array.isArray(sourceModel?.items)?sourceModel.items:[]}
function modelMedia(){return sourceItems().filter(item=>item?.[2]==='image'||item?.[2]==='video').map(item=>({hash:String(item[0]||''),filename:String(item[1]||''),type:String(item[2]||'image'),width:Number(item[3])||0,height:Number(item[4])||0,dateMs:Number(item[5])||0,size:Number(item[6])||0})).filter(item=>/^[a-f0-9]{64}$/.test(item.hash))}
function isSourceSnapshot(snapshot){const value=String(snapshot?.sort||'');return snapshot&&Array.isArray(snapshot.items)&&!value.startsWith('experimental-result')&&!value.startsWith('ai-global-result')&&!value.startsWith('visual-flow')&&!value.startsWith('similarity')}
function captureSource(snapshot){if(!isSourceSnapshot(snapshot))return;sourceModel=snapshot;if(wanted)scheduleRun(30)}
function wrapGrid(){const grid=window.mochimonoStableGrid;if(!grid){requestAnimationFrame(wrapGrid);return}if(wrappedGrid===grid)return;wrappedGrid=grid;baseSetModel=grid.setModel.bind(grid);grid.setModel=snapshot=>{if(wanted&&isSourceSnapshot(snapshot)){if(String(snapshot.sort||'')!=='experimental'){deactivate();return baseSetModel(snapshot)}captureSource(snapshot);return true}return baseSetModel(snapshot)};if(wanted&&isSourceSnapshot(window.mochimonoGridModel))captureSource(window.mochimonoGridModel)}
function removeCard(index,element=mounted.get(index)){if(!element)return;element.querySelector('img')?.removeAttribute('src');element.remove();mounted.delete(index)}
function clearMounted(){for(const[index,element]of mounted)removeCard(index,element);mounted.clear()}
function destroyMapRenderer(){if(!mapRenderer)return;mapRenderer.destroy();mapRenderer=null;mapCanvas.hidden=true}
function cancelRun(){generation++;clearTimeout(runTimer);runTimer=0;clearTimeout(mapSettleTimer);mapSettleTimer=0;if(worker){try{worker.postMessage({action:'cancel'})}catch{}try{worker.terminate()}catch{}worker=null}}
function deactivate(){wanted=false;cancelRun();document.documentElement.classList.remove('experimental-view-active');bar.hidden=true;surface.hidden=true;files.hidden=false;viewport.classList.remove('dragging','over-media');viewport.title='';drag=null;clearMounted();destroyMapRenderer();result=null;roomsLayer.replaceChildren();setLoading('');if(renderFrame)cancelAnimationFrame(renderFrame);renderFrame=0}
function activate(){wanted=true;document.documentElement.classList.add('experimental-view-active');bar.hidden=false;surface.hidden=false;files.hidden=true;syncButtons();captureSource(window.mochimonoGridModel);scheduleRun(20)}
function currentCell(){return Math.max(64,Math.min(132,Number(mediaSize?.value)||96))}
function columnsForMosaic(){return Math.max(2,Math.floor(Math.max(320,viewport.clientWidth-8)/currentCell()))}
function cacheKey(){return`${mode}:${mediaIdentity(media)}${mode==='mosaic'?`:${columnsForMosaic()}`:''}:tight4`}
function remember(key,value){cache.delete(key);cache.set(key,value);while(cache.size>5)cache.delete(cache.keys().next().value)}
function workerForMode(selectedMode){const file=selectedMode==='semantic-rooms'?`./ai-global-sort-topics-worker.js?v=${WORKER_REV}`:`./experimental-layout-worker-dense.js?v=${WORKER_REV}`;return new Worker(new URL(file,import.meta.url),{type:'module'})}
function runWorker(selectedMode,items,columns){return new Promise((resolve,reject)=>{const target=workerForMode(selectedMode);worker=target;const myGeneration=generation;target.onerror=event=>reject(new Error(event.message||'Experimental layout worker failed'));target.onmessageerror=()=>reject(new Error('Experimental layout worker returned unreadable data'));target.onmessage=event=>{if(myGeneration!==generation)return;const data=event.data||{};if(data.type==='progress'){setStatus(data.detail||`Building ${MODES[selectedMode].label}…`);return}if(data.type==='error'){const error=new Error(data.error||'Could not build experimental view');if(data.aborted)error.name='AbortError';reject(error);return}if(data.type==='result')resolve(data.result||{})};target.postMessage({action:selectedMode==='semantic-rooms'?'sort':'build',payload:{mode:selectedMode,media:items,columns}})})}

function tightRoom(members,items){
  const total=members.reduce((s,i)=>s+layoutRatio(items[i]),0),target=Math.max(3,Math.sqrt(Math.max(1,total))),gap=.018,rows=[];let row=[],sum=0;
  const finish=()=>{if(row.length){rows.push(row);row=[];sum=0}};
  for(const index of members){const r=layoutRatio(items[index]);if(row.length&&sum>=target*.75&&Math.abs(target-(sum+r))>Math.abs(target-sum))finish();row.push(index);sum+=r;if(sum>=target*1.08)finish()}finish();
  const placed=[];let top=.12,maxRight=0;
  for(const current of rows){const rs=current.reduce((s,i)=>s+layoutRatio(items[i]),0),usable=Math.max(.1,target-gap*Math.max(0,current.length-1)),h=Math.min(1.08,usable/Math.max(.001,rs));let left=.12;for(const index of current){const boxW=layoutRatio(items[index])*h,[w,actualH]=fitAspect(items[index],boxW,h);placed.push({index,x:left+boxW/2,y:top+h/2,w,h:actualH});left+=boxW+gap}maxRight=Math.max(maxRight,left-gap);top+=h+gap}
  return{placed,w:Math.max(.3,maxRight+.12),h:Math.max(.3,top-gap+.12)};
}
function packSemanticRooms(topicResult,items){
  const byHash=new Map(items.map((item,index)=>[item.hash,index])),order=(topicResult.order||[]).map(hash=>byHash.get(hash)).filter(Number.isInteger),rails=(topicResult.rail||[]).slice().sort((a,b)=>a.index-b.index),groups=[],classifiedEnd=Math.max(0,Math.min(order.length,Number(topicResult.indexed)||order.length));
  for(let r=0;r<rails.length;r++){const start=Math.max(0,Number(rails[r].index)||0),end=r+1<rails.length?Math.max(start,Math.min(classifiedEnd,Number(rails[r+1].index)||0)):classifiedEnd;groups.push({label:String(rails[r].label||`Room ${r+1}`),members:order.slice(start,end)})}const other=order.slice(classifiedEnd);if(other.length)groups.push({label:'Other',members:other});
  const packed=groups.filter(g=>g.members.length).map(group=>({...group,...tightRoom(group.members,items)})),area=packed.reduce((s,g)=>s+g.w*g.h,0),targetW=Math.max(8,Math.sqrt(area*1.25)),x=new Float32Array(items.length),y=new Float32Array(items.length),renderW=new Float32Array(items.length),renderH=new Float32Array(items.length),labels=[];x.fill(-1);y.fill(-1);
  let px=.5,py=.5,rowH=0,worldW=1;
  for(const group of packed){if(px>.5&&px+group.w>targetW+.5){px=.5;py+=rowH+.22;rowH=0}for(const p of group.placed){const cx=px+p.x,cy=py+p.y;x[p.index]=cx-.5;y[p.index]=cy-.5;renderW[p.index]=p.w;renderH[p.index]=p.h}labels.push({x:px-.5,y:py-.5,w:group.w,h:group.h,label:group.label});px+=group.w+.22;rowH=Math.max(rowH,group.h);worldW=Math.max(worldW,px)}
  return{kind:'map',x,y,renderW,renderH,worldW:worldW+.28,worldH:py+rowH+.5,labels,detail:`Semantic Rooms · ${packed.length} named regions · tight aspect packing`};
}

async function run(){if(!wanted||!sourceModel)return;cancelRun();const myGeneration=++generation;media=modelMedia();if(!media.length){setStatus('No image or video media in this view');setLoading('No media');return}cell=currentCell();gridColumns=columnsForMosaic();const key=cacheKey(),cached=cache.get(key);if(cached){result=cached;installResult();return}setLoading(`Building ${MODES[mode].label}…`);setStatus(`Building ${MODES[mode].label}…`);try{let built=await runWorker(mode,media,gridColumns);if(myGeneration!==generation||!wanted)return;if(mode==='semantic-rooms')built=packSemanticRooms(built,media);result=built;remember(key,built);installResult()}catch(error){if(error?.name==='AbortError'||myGeneration!==generation)return;console.error(error);setStatus(error.message||String(error));setLoading(error.message||String(error))}finally{if(worker){try{worker.terminate()}catch{}worker=null}}}
function scheduleRun(delay=80){clearTimeout(runTimer);runTimer=setTimeout(run,delay)}
function makeCard(index,left,top,size){const item=media[index];if(!item)return null;const button=document.createElement('button');button.className='experimental-card';button.type='button';button.dataset.index=String(index);button.title=item.filename||item.hash;button.style.left=`${left}px`;button.style.top=`${top}px`;button.style.width=`${size}px`;button.style.height=`${size}px`;button.innerHTML=`<img alt="" draggable="false" loading="lazy" decoding="async" fetchpriority="low" src="/api/thumbs/${encodeURIComponent(item.hash)}?v=${THUMB_VERSION}">`;button.addEventListener('click',event=>{event.stopPropagation();window.mochimonoOpenViewer?.(item.hash,item)});cardsLayer.append(button);mounted.set(index,button);return button}
function reconcileGrid(wantedIndexes,positionFor,size){const wantedSet=new Set(wantedIndexes);for(const[index,element]of mounted)if(!wantedSet.has(index))removeCard(index,element);for(const index of wantedIndexes){if(mounted.has(index))continue;const point=positionFor(index);if(point)makeCard(index,point[0],point[1],size)}}
function scheduleRender(){if(!renderFrame)renderFrame=requestAnimationFrame(()=>{renderFrame=0;renderGrid()})}
function renderGrid(){const order=result?.order;if(!order?.length)return;const startRow=Math.max(0,Math.floor(viewport.scrollTop/cell)-2),endRow=Math.ceil((viewport.scrollTop+viewport.clientHeight)/cell)+2,start=Math.min(order.length,startRow*gridColumns),end=Math.min(order.length,endRow*gridColumns),indexes=[];for(let p=start;p<end;p++)indexes.push(Number(order[p]));reconcileGrid(indexes,index=>{const pos=indexPosition.get(index);return pos==null?null:[(pos%gridColumns)*cell,Math.floor(pos/gridColumns)*cell]},Math.max(28,cell-4))}
function ensureMapRenderer(){if(mapRenderer)return true;try{mapRenderer=new ExperimentalWebGLMapRenderer(mapCanvas,{thumbVersion:THUMB_VERSION,onError:error=>console.debug('Experimental WebGL thumbnail:',error)});return true}catch(error){console.error(error);setStatus(error.message||String(error));setLoading(error.message||String(error));return false}}
function applyMapTransform(){plane.style.transform=`translate(${mapPanX}px,${mapPanY}px) scale(${mapZoom})`;mapRenderer?.setCamera(mapPanX,mapPanY,mapZoom)}
function settleMap(){mapRenderer?.setCamera(mapPanX,mapPanY,mapZoom);mapRenderer?.settle()}
function scheduleMapSettle(delay=60){clearTimeout(mapSettleTimer);mapSettleTimer=setTimeout(()=>{mapSettleTimer=0;settleMap()},delay)}
function fitMap(){if(!result||result.kind!=='map'||!mapRenderer)return;const worldW=Math.max(1,Number(result.worldW))*cell,worldH=Math.max(1,Number(result.worldH))*cell,vw=Math.max(1,viewport.clientWidth),vh=Math.max(1,viewport.clientHeight);mapZoom=Math.max(.025,Math.min(1.25,Math.min(vw/worldW,vh/worldH)*.96));mapPanX=(vw-worldW*mapZoom)/2;mapPanY=(vh-worldH*mapZoom)/2;applyMapTransform();settleMap()}
function renderLabels(){roomsLayer.replaceChildren();const labels=Array.isArray(result?.labels)?result.labels:[],roomMode=mode==='family-quilt'||mode==='semantic-rooms',limited=labels.length>600?labels.filter((_,i)=>i%Math.ceil(labels.length/600)===0):labels;for(const entry of limited){const node=document.createElement('div');if(roomMode){node.className='experimental-view-room';node.style.left=`${Number(entry.x)*cell}px`;node.style.top=`${Number(entry.y)*cell}px`;node.style.width=`${Math.max(.1,Number(entry.w))*cell}px`;node.style.height=`${Math.max(.1,Number(entry.h))*cell}px`;node.innerHTML=`<span>${escapeHtml(entry.label)}</span>`}else{node.className='experimental-view-marker';node.style.left=`${Number(entry.x)*cell+4}px`;node.style.top=`${Number(entry.y)*cell+4}px`;node.textContent=entry.label}roomsLayer.append(node)}}
function installResult(){clearMounted();indexPosition=new Map();setLoading('');cell=currentCell();syncButtons();if(result.kind==='grid'){destroyMapRenderer();fitButton.hidden=true;mapCanvas.hidden=true;cardsLayer.hidden=false;viewport.classList.add('grid-mode');viewport.classList.remove('over-media');viewport.title='';viewport.scrollTop=0;plane.style.transform='none';const order=result.order||[];for(let p=0;p<order.length;p++)indexPosition.set(Number(order[p]),p);const rows=Math.ceil(order.length/gridColumns);plane.style.width=`${gridColumns*cell}px`;plane.style.height=`${Math.max(1,rows)*cell}px`;roomsLayer.replaceChildren();setStatus(result.detail||MODES[mode].description);renderGrid()}else{fitButton.hidden=false;cardsLayer.hidden=true;viewport.classList.remove('grid-mode');viewport.scrollTop=0;plane.style.width=`${Math.max(1,Number(result.worldW))*cell}px`;plane.style.height=`${Math.max(1,Number(result.worldH))*cell}px`;renderLabels();if(!ensureMapRenderer())return;mapCanvas.hidden=false;mapRenderer.resize();mapRenderer.setScene({media,result,cell});setStatus(`${result.detail||MODES[mode].description} · WebGL2`);fitMap()}surface.hidden=false}
function localPoint(event){const rect=viewport.getBoundingClientRect();return[event.clientX-rect.left,event.clientY-rect.top]}
function updateHover(event){if(result?.kind!=='map'||!mapRenderer||drag)return;const[x,y]=localPoint(event),index=mapRenderer.hitTest(x,y);mapRenderer.setHover(index);viewport.classList.toggle('over-media',index>=0);viewport.title=index>=0?(media[index]?.filename||''):''}
bar.addEventListener('click',event=>{const button=event.target.closest('[data-experimental-mode]');if(button){const next=button.dataset.experimentalMode;if(!MODES[next]||next===mode)return;mode=next;localStorage.setItem(MODE_KEY,mode);syncButtons();scheduleRun(10);return}if(event.target.closest('.experimental-view-fit'))fitMap();if(event.target.closest('.experimental-view-close')){deactivate();window.mochimonoLibrary?.setSort?.('date-desc')}});
sort?.addEventListener('change',()=>{const next=sort.value==='experimental';if(next&&!wanted)activate();else if(!next&&wanted)deactivate()});viewport.addEventListener('scroll',()=>{if(result?.kind==='grid')scheduleRender()},{passive:true});
viewport.addEventListener('wheel',event=>{if(result?.kind!=='map'||!mapRenderer)return;event.preventDefault();const[cx,cy]=localPoint(event),worldX=(cx-mapPanX)/mapZoom,worldY=(cy-mapPanY)/mapZoom,next=Math.max(.025,Math.min(MAX_MAP_ZOOM,mapZoom*Math.exp(-event.deltaY*.0015)));mapPanX=cx-worldX*next;mapPanY=cy-worldY*next;mapZoom=next;applyMapTransform();scheduleMapSettle()},{passive:false});
viewport.addEventListener('pointerdown',event=>{if(result?.kind!=='map'||event.button!==0)return;drag={id:event.pointerId,x:event.clientX,y:event.clientY,panX:mapPanX,panY:mapPanY,moved:false};viewport.classList.remove('over-media');event.preventDefault()});
viewport.addEventListener('pointermove',event=>{if(!drag||drag.id!==event.pointerId){updateHover(event);return}const dx=event.clientX-drag.x,dy=event.clientY-drag.y;if(!drag.moved&&Math.hypot(dx,dy)<4)return;if(!drag.moved){drag.moved=true;viewport.classList.add('dragging');mapRenderer?.setHover(-1);try{viewport.setPointerCapture(event.pointerId)}catch{}}mapPanX=drag.panX+dx;mapPanY=drag.panY+dy;applyMapTransform();event.preventDefault()});
viewport.addEventListener('pointerup',event=>{if(!drag||drag.id!==event.pointerId)return;const moved=drag.moved;drag=null;viewport.classList.remove('dragging');if(!moved&&mapRenderer){const[x,y]=localPoint(event),index=mapRenderer.hitTest(x,y);if(index>=0){const item=media[index];window.mochimonoOpenViewer?.(item.hash,item)}}scheduleMapSettle(0);updateHover(event)});viewport.addEventListener('pointercancel',()=>{drag=null;viewport.classList.remove('dragging');scheduleMapSettle(0)});viewport.addEventListener('pointerleave',()=>{if(drag)return;mapRenderer?.setHover(-1);viewport.classList.remove('over-media');viewport.title=''});
new ResizeObserver(()=>{if(!wanted||!result)return;if(mode==='mosaic'&&columnsForMosaic()!==gridColumns)scheduleRun(220);else if(result.kind==='map'){mapRenderer?.resize();fitMap()}else scheduleRender()}).observe(viewport);window.addEventListener('mochimono:media-size',()=>{if(!wanted)return;cell=currentCell();mode==='mosaic'?scheduleRun(120):installResult()});
window.mochimonoExperimentalViews={active:()=>wanted,mode:()=>mode,rerun:()=>scheduleRun(0),state:()=>({active:wanted,mode,count:media.length,kind:result?.kind||'',mounted:mounted.size,zoom:mapZoom,maxZoom:MAX_MAP_ZOOM,renderer:mapRenderer?.stats?.()||null})};
wrapGrid();syncButtons();if(sort?.value==='experimental')activate();
